"""Add cloudinary image fields to projects table

Revision ID: 182c97671704
Revises: 7d3f494f0e2e
Create Date: 2025-08-02 16:16:12.909910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182c97671704'
down_revision: Union[str, Sequence[str], None] = '7d3f494f0e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('image_public_id', sa.String(), nullable=True))
    op.drop_column('projects', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'image_public_id')
    op.drop_column('projects', 'image_url')
    # ### end Alembic commands ###
