"""Add github_url, live_url, and image_path to projects

Revision ID: 7d3f494f0e2e
Revises: 703bc7df0e2e
Create Date: 2025-07-31 12:37:02.386382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3f494f0e2e'
down_revision: Union[str, Sequence[str], None] = '703bc7df0e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('github_url', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('live_url', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'image_path')
    op.drop_column('projects', 'live_url')
    op.drop_column('projects', 'github_url')
    # ### end Alembic commands ###
